{{ $terraform := index .config.tools "hashicorp/terraform" -}}
{{ $tflint := index .config.tools "terraform-linters/tflint" -}}
{{ $tflint_aws := index .config.tools "terraform-linters/tflint-ruleset-aws" -}}
{{ $tfsec := index .config.tools "aquasecurity/tfsec" -}}
{{ $terraform_docs := index .config.tools "terraform-docs/terraform-docs" -}}
{{ $terrascan := index .config.tools "accurics/terrascan" -}}
{{ $just := index .config.tools "casey/just" -}}
{{ $direnv := index .config.tools "direnv/direnv" -}}
{{ $1password := index .config.tools "1password" -}}
{{ $kubectl := index .config.tools "kubernetes/kubectl" -}}

FROM {{ .config.image }} as core
# hadolint ignore=DL3018
RUN apk add --update --no-cache \
    bash curl git openssh openssh-client jq graphviz ncurses nano libc6-compat {{ join .config.extraPackages " " }}

SHELL ["/bin/bash", "-o", "pipefail", "-c"]

ENV EDITOR nano

FROM core as terraform
RUN curl -L https://releases.hashicorp.com/terraform/{{ $terraform }}/terraform_{{ $terraform }}_linux_amd64.zip -o /tmp/terraform.zip \
    && unzip /tmp/terraform.zip -d /tmp/ && rm /tmp/terraform.zip

FROM core as tflint
RUN curl -L https://github.com/terraform-linters/tflint/releases/download/v{{ $tflint }}/tflint_linux_amd64.zip -o /tmp/tflint.zip \
    && unzip /tmp/tflint.zip -d /tmp/ && rm /tmp/tflint.zip

FROM core as tflint_aws
RUN curl -L https://github.com/terraform-linters/tflint-ruleset-aws/releases/download/v{{ $tflint_aws }}/tflint-ruleset-aws_linux_amd64.zip  -o /tmp/tflint-ruleset-aws.zip \
    && unzip /tmp/tflint-ruleset-aws.zip -d /tmp/ && rm /tmp/tflint-ruleset-aws.zip

FROM core as tfsec
RUN curl -L https://github.com/aquasecurity/tfsec/releases/download/v{{ $tfsec }}/tfsec-linux-amd64 -o /tmp/tfsec \
    && chmod +x /tmp/tfsec

FROM core as terraform_docs
RUN curl -L https://github.com/terraform-docs/terraform-docs/releases/download/v{{ $terraform_docs }}/terraform-docs-v{{ $terraform_docs }}-linux-amd64 -o /tmp/terraform-docs \
    && chmod +x /tmp/terraform-docs

FROM core as terrascan
RUN curl -L https://github.com/accurics/terrascan/releases/download/v{{ $terrascan }}/terrascan_{{ $terrascan }}_Linux_x86_64.tar.gz -o /tmp/terrascan.tar.gz \
    && cd /tmp && tar -xf /tmp/terrascan.tar.gz terrascan && rm /tmp/terrascan.tar.gz

FROM core as just
# hadolint ignore=DL4006
RUN curl --proto '=https' --tlsv1.2 -sSf https://just.systems/install.sh | bash -s -- --to /tmp/ --tag {{ $just }}

FROM core as direnv
RUN curl -L https://github.com/direnv/direnv/releases/download/v{{ $direnv }}/direnv.linux-amd64 -o /tmp/direnv \
    && chmod +x /tmp/direnv

FROM core as op
RUN curl -L https://cache.agilebits.com/dist/1P/op/pkg/v{{ $1password }}/op_linux_amd64_v{{ $1password }}.zip -o /tmp/op.zip \
    && unzip /tmp/op.zip -d /tmp/ && rm /tmp/op.zip

FROM core as kubectl
RUN curl -L https://storage.googleapis.com/kubernetes-release/release/v{{ $kubectl }}/bin/linux/amd64/kubectl -o /tmp/kubectl \
    && chmod +x /tmp/kubectl

FROM core

RUN apk add --no-cache \
        python3 \
        py3-pip \
    && pip3 install --upgrade pip \
    && pip3 install --no-cache-dir \
        awscli \
    && rm -rf /var/cache/apk/*

RUN sh -c "$(curl -fsSL https://starship.rs/install.sh)" -- -y

ENV VERSIONS='{ \
  "hashicorp/terraform":"v{{ $terraform }}", \
  "terraform-linters/tflint":"v{{ $tflint }}", \
  "terraform-linters/tflint-ruleset-aws":"v{{ $tflint_aws }}", \
  "aquasecurity/tfsec":"v{{ $tfsec }}", \
  "terraform-docs/terraform-docs":"v{{ $terraform_docs }}", \
  "accurics/terrascan":"v{{ $terrascan }}", \
  "casey/just":"{{ $just }}", \
  "direnv/direnv":"v{{ $direnv }}" \
}'

COPY --from=terraform /tmp/terraform /usr/local/bin/terraform
COPY --from=tflint /tmp/tflint /usr/local/bin/tflint
COPY --from=tflint_aws /tmp/tflint-ruleset-aws $TFLINT_PLUGIN_DIR/tflint-ruleset-aws
COPY --from=tfsec /tmp/tfsec /usr/local/bin/tfsec
COPY --from=terraform_docs /tmp/terraform-docs /usr/local/bin/terraform-docs
COPY --from=terrascan /tmp/terrascan /usr/local/bin/terrascan
COPY --from=just /tmp/just /usr/local/bin/just
COPY --from=direnv /tmp/direnv /usr/local/bin/direnv
COPY --from=op /tmp/op /usr/local/bin/op
COPY --from=kubectl /tmp/kubectl /usr/local/bin/kubectl

RUN adduser -h /home/user -s /bin/bash -u 1000 -D user

RUN echo 'eval "$(direnv hook bash)"; eval $(ssh-agent); ssh-add; eval "$(starship init bash)"' > /home/user/.bashrc

ENV PS1 '\s-\v:\w\$ '
ENV PATH="/terraform/.meta/bin:${PATH}"
ENV DIRENV_CONFIG="/terraform/.meta/direnv"
ENV STARSHIP_CONFIG="/terraform/.meta/starship/config.toml"

ENTRYPOINT []
