add_newline = true
format = "[ vtvz's workspace ](bg:#1380EC fg:#1e1e1e bold) $all$directory$character"

[terraform]
symbol = "tf "

[aws]
symbol = "aws "
format = 'on [$symbol($profile )(\($region\) )(\[$duration\] )]($style)'

[kubernetes]
disabled = false
format = '[$symbol$context( \($namespace\))]($style) '

[kubernetes.context_aliases]
"arn:aws:eks:.*:.*:cluster/(.*)" = "$1"

[directory]
style = "dimmed"

[status]
disabled = false
