add_newline = true

[aws]
symbol = "aws "
format = 'on [$symbol($profile )(\($region\) )(\[$duration\] )]($style)'

[kubernetes]
disabled = false

[kubernetes.context_aliases]
"arn:aws:eks:.*:.*:cluster/(.*)" = "$1"

