add_newline = true
format = "$custom$all$directory$status$character"

[character]                            # The name of the module we are configuring is "character"
success_symbol = "[>](bold green)"
error_symbol = "[>](bold red)"
vicmd_symbol = "[<](bold green)"

[terraform]
symbol = "tf "

[aws]
symbol = "aws "
format = 'on [$symbol($profile )(\($region\) )(\[$duration\] )]($style)'

[kubernetes]
disabled = false
format = '[$symbol$context( \($namespace\))]($style) '

[kubernetes.context_aliases]
"arn:aws:eks:.*:.*:cluster/(.*)" = "$1"

[directory]
style = "dimmed"

[status]
disabled = false
symbol = "x"
success_symbol = "v"
pipestatus = true
style = "white"

[custom.me]
command = "whoami"
when = "true"
format = "[ $output's workspace ](bg:#1380EC fg:#1e1e1e bold) "

[git_branch]
disabled = true

[git_commit]
disabled = true

[git_state]
disabled = true

[git_status]
disabled = true

[container]
disabled = true

[time]
disabled = false
format = "[$time]($style) "
