services:
  workspace:
    build:
      context: .
      dockerfile: .ws/var/Dockerfile
      args:
        workdir: /workspace
    volumes:
      - .:/workspace
      - ~/.ssh:/home/user/.ssh
      - .ws/var/op:/home/user/.config/op
      - .ws/var/kube:/home/user/.kube
      - .ws/tools/.tflint.hcl:/home/user/.tflint.hcl
      - .ws/var/zsh:/home/user/.zsh_tmp
      - .ws/var/jump:/home/user/.jump
      - .ws/var/packer:/home/user/.config/packer
      - .ws/var/helm:/home/user/.cache/helm
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - .env
      - .ws.env
    environment:
      AWS_VAULT: ${AWS_VAULT:-}
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION:-}
      AWS_REGION: ${AWS_REGION:-}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID:-}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY:-}
      AWS_SESSION_TOKEN: ${AWS_SESSION_TOKEN:-}
      AWS_SESSION_EXPIRATION: ${AWS_SESSION_EXPIRATION:-}
      AWS_SECURITY_TOKEN: ${AWS_SECURITY_TOKEN:-}
      AWS_CREDENTIAL_EXPIRATION: ${AWS_CREDENTIAL_EXPIRATION:-}
      IN_DOCKER: "true"
      TERM: xterm-256color
    restart: "no"
    user: "1000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
