version: "3.8"
services:
  workspace:
    build:
      context: .
      dockerfile: .meta/var/Dockerfile
      args:
        workdir: /workspace
    volumes:
      - .:/workspace
      - ~/.ssh:/home/user/.ssh
      - .meta/var/op:/home/user/.config/op
      - .meta/nvim:/home/user/.config/nvim
      - .meta/zellij:/home/user/.config/zellij
      - .meta/var/kube:/home/user/.kube
      - .meta/.tflint.hcl:/home/user/.tflint.hcl
      - .meta/var/.bash_history:/home/user/.bash_history
      - .meta/var/zsh:/home/user/.zsh_tmp
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - .env
    environment:
      AWS_VAULT: ${AWS_VAULT:-}
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION:-}
      AWS_REGION: ${AWS_REGION:-}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID:-}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY:-}
      AWS_SESSION_TOKEN: ${AWS_SESSION_TOKEN:-}
      AWS_SESSION_EXPIRATION: ${AWS_SESSION_EXPIRATION:-}
      AWS_SECURITY_TOKEN: ${AWS_SECURITY_TOKEN:-}
      IN_DOCKER: "true"
      TERM: xterm-256color
    restart: "no"
    user: "1000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
