version: "3.8"
services:
  terraform:
    build:
      context: .
      dockerfile: .meta/var/Dockerfile
    volumes:
      - .:/terraform
      - ~/.ssh:/home/user/.ssh
      - .meta/var/op:/home/user/.config/op
      - .meta/var/kube:/home/user/.kube
      - .meta/.tflint.hcl:/home/user/.tflint.hcl
    env_file:
      - .env
    environment:
      AWS_VAULT: $AWS_VAULT
      AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
      AWS_REGION: $AWS_REGION
      AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
      AWS_SESSION_TOKEN: $AWS_SESSION_TOKEN
      AWS_SESSION_EXPIRATION: $AWS_SESSION_EXPIRATION
      AWS_SECURITY_TOKEN: $AWS_SECURITY_TOKEN
      IN_DOCKER: "true"
    restart: "Never"
    working_dir: /terraform
    user: "1000"
